"""new database relationship

Revision ID: 9d07df0cbecf
Revises: 1be517642fd3
Create Date: 2019-03-06 00:45:13.615841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d07df0cbecf'
down_revision = '1be517642fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_model', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_model', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=100), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    op.drop_constraint(None, 'stock_model', type_='foreignkey')
    op.drop_column('stock_model', 'user_id')
    # ### end Alembic commands ###
